### ISSUE TITLE
Mongodb Store does not clear expired docs in the ratelimits collection.

### ISSUE THREAD

**Issue by fehimismailov** [ysocorp/koa2-ratelimit#16]
The following function is supposed to clean all the existing documents in the ratelimits collection where dateEnd <= now, but it does not. Therefore once a limit is reached, it stays there forever. 

`async _removeAll() {
        await this.Ratelimits.remove({ dateEnd: { $lte: Date.now() } });
    }`

**Comment by julienwilmet** [comment]
There are two tables as you can see [here](https://github.com/ysocorp/koa2-ratelimit#use-with-mongoosestore-mongodb): `ratelimits` and `ratelimitsabuses`. If it is the second one, they will indeed stay there forever since the goal of this table is to allow you to act on the reached limits.

 If you want to remove them too, you can write a PR to add this behaviour as an option.

**Comment by waifutech** [comment]
Encountered the same problem. Store saves dates as unix time, while declaring it as date. Mongoose seems to convert it to date for `remove` query but not when saving.

Calling `remove` directly on collection is the least invasive quick fix:

```
Stores.Mongodb.prototype._removeAll = async function() {
    await this.Ratelimits.collection.remove({ dateEnd: { $lte: Date.now() } });
}
```

```
    "mongoose": "^5.11.15",
    "koa2-ratelimit": "^0.9.0",
```
